name: Format

on: [push, pull_request]

jobs:
  prettier-format-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install frontend dependencies
        run: npm ci

      - name: Format js/ts files
        run: npm run format

      - name: Build frontend
        if: ${{ github.ref == "refs/heads/staging" }}
        run: npm run build


  black-format:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install backend dependencies
        run: python -m pip install --upgrade pip black

      - name: Format py files
        run: black --target-version=py39 **/*.py *.py

  commit-changes:
    needs: [prettier-format-build, black-format]
    runs-on: ubuntu-latest
    steps:
      uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-apply formatting and/or build
          branch: ${{ github.head_ref }}
