name: Format

on: [push, pull_request]

jobs:
  prettier-format-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Format js/ts files
        run: |
          npm install --save-dev prettier
          npm run format

      - name: Build frontend
        if: ${{ github.ref == "refs/heads/staging" }}
        run: |
          npm ci
          npm run build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-apply js/ts formatting and/or build
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



  black-format:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install backend dependencies
        run: python -m pip install --upgrade pip black

      - name: Format py files
        run: black --target-version=py39 **/*.py *.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-apply Python formatting
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
